---
#core group use v1
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  labels:
    name: bggdb-svc
spec:
  type: LoadBalancer
  selector:
    name: bgg-database-po
  ports:
  - port: 3306 # service port
    targetPort: dov-port-db # container port 3000
