---
#core group use v1
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels:
    name: bggapp-svc
spec:
  type: LoadBalancer
  selector:
    name: bggapp-deploy-po
  ports:
  - port: 80 # service port
    targetPort: dov-port # container port 3000
