---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-bear-deploy
  labels:
    name: dov-bear-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      name: dov-bear-po
  template:
    metadata:
      name: dov-bear-po
      labels:
        name: dov-bear-po
    spec:
      containers:
      - name: dov-bear-container
        image: chukmunnlee/dov-bear:v2
        imagePullPolicy: IfNotPresent
        envFrom:
         - secretRef:
             name: dov-bear-secret
        ports:
         - name: dov-port
           containerPort: 3000
        livenessProbe:
         httpGet:
           path: /healthz
           port: 3000
           scheme: HTTP
          
