---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-vol
  labels:
    name: my-vol
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
